ScreenData.GhostAdmin.ItemCategories =
{
	{
		Name = "WorldUpgradeScreen_Critical",
		Icon = "GUI\\Screens\\CriticalItemShop\\Icon-Incantations",
		Animations = { Default = "GUI\\Screens\\CriticalItemShop\\CategoryTab01", Highlight = "GUI\\Screens\\CriticalItemShop\\CategoryTabMouseOver01", Active = "GUI\\Screens\\CriticalItemShop\\CategoryTabSelected01" },
		OneRevealPerRun = true,
		GameStateRequirements =
		{
			-- None
		},
		-- story & major progression
		"WorldUpgradeStormStop",
		"WorldUpgradeTimeStop",
		"WorldUpgradeSurfacePenaltyCure",
		"WorldUpgradeAltRunDoor",
		"WorldUpgradeQuestLog",
		"WorldUpgradeMorosUnlock",
		"WorldUpgradeNarcissusWaters",
		"WorldUpgradeDoraMemory",
		"WorldUpgradeMedeaTears",
		"WorldUpgradeSkellyHealth",
		"WorldUpgradeWakeHypnos",
		"WorldUpgradeWakeHypnosT2",
		"WorldUpgradeWakeHypnosT3", -- @ ending
		-- deferred story further down

		-- key systems
		"WorldUpgradeWeaponUpgradeSystem",
		"WorldUpgradeCardUpgradeSystem",
		"WorldUpgradeBountyBoard",
		"WorldUpgradeBountyBoardRepeat",
		"WorldUpgradeFamiliarSystem",
		"WorldUpgradeFamiliarUpgradeSystem",
		"WorldUpgradeFamiliarCostumeSystem",
		"WorldUpgradeToolUpgradeSystem",
		"WorldUpgradeBadgeSeller",
		"WorldUpgradeChangeNextRunRNG",

		-- key upgrades
		"WorldUpgradeToolsShop",
		"WorldUpgradeElementalBoons",
		"WorldUpgradePinning",
		"WorldUpgradePinningBoons",
		"WorldUpgradeMetaUpgradeSaveLayout",
		"WorldUpgradeKeepsakeSaveFirst",
		"WorldUpgradeResourceFinder",
		"WorldUpgradeBoonList",
		"WorldUpgradeMarket",
		"WorldUpgradeSellShop",
		"WorldUpgradeGiftsShop",
		"WorldUpgradeExchangeShop",

		-- run upgrades
		"WorldUpgradeBossDifficultyT2",
		"WorldUpgradeBossDifficultyT3",
		"WorldUpgradeBossDifficultyT4",
		"WorldUpgradeFountainUpgrade1",
		"WorldUpgradeFountainUpgrade2",
		"WorldUpgradeWellShops",
		"WorldUpgradePostBossWellShops",
		"WorldUpgradeSurfaceShops",
		"WorldUpgradePostBossSurfaceShops",
		"WorldUpgradeRestoreSellTraitShop",
		"WorldUpgradePostBossSellTraitShops",
		"WorldUpgradeErebusReprieve",
		"WorldUpgradeOceanusReprieve",
		"WorldUpgradeTartarusReprieve",
		"WorldUpgradeThessalyReprieve",
		"WorldUpgradeOlympusReprieve",
		"WorldUpgradeBreakableValue1",
		"WorldUpgradeEphyraZoomOut",
		"WorldUpgradeFieldsRewardFinder",
		"WorldUpgradeTimeSlowChronosFight",
		"WorldUpgradePauseChronosFight",
		"WorldUpgradeUnusedWeaponBonus",
		"WorldUpgradeUnusedWeaponBonusT2",
		"WorldUpgradePostBossGiftRack",
		"WorldUpgradeDoubleAdvanceKeepsakes",
		"WorldUpgradeOlympusStatues",
		"WorldUpgradeErebusSafeZones",
		"WorldUpgradeSafeZoneSpellCharge",
		"WorldUpgradeShadeMercs",
		"WorldUpgradeChallengeSwitches1",
		"WorldUpgradeChallengeSwitchesExtra1",
		"WorldUpgradeChallengeSwitchesSurface1",
		"WorldUpgradeMetaRewardStands",
		"WorldUpgradeMetaCardPointsCommonRunProgress",
		"WorldUpgradeMetaCurrencyRunProgress",
		"WorldUpgradeGiftDropRunProgress",

		-- hub expansions
		"WorldUpgradeTaverna",
		"WorldUpgradeBathHouse",
		"WorldUpgradeFishingPoint",

		-- supporting systems
		"WorldUpgradeHarvestUpgrade",
		"WorldUpgradeGarden",
		"WorldUpgradeGardenT2",
		"WorldUpgradeGardenT3",
		"WorldUpgradeGardenHarvestAll",
		"WorldUpgradeGardenMultiPlant",
		"WorldUpgradeAutoHarvestOnExit",
		"WorldUpgradeRelationshipBar",
		"WorldUpgradeMusicPlayer",
		"WorldUpgradeMusicPlayerShuffle",
		"WorldUpgradeRunHistory",
		"WorldUpgradeGameStats",
		"WorldUpgradeStoryReset",
		"WorldUpgradeErisTrashPickup",
	},		
	{
		Name = "WorldUpgradeScreen_Repeatable",
		Icon = "GUI\\Screens\\CriticalItemShop\\Icon-Alchemy",
		Animations = { Default = "GUI\\Screens\\CriticalItemShop\\CategoryTab02", Highlight = "GUI\\Screens\\CriticalItemShop\\CategoryTabMouseOver02", Active = "GUI\\Screens\\CriticalItemShop\\CategoryTabSelected02", Reveal = "CriticalItemShopCategoryTabReveal", },
		GameStateRequirements =
		{
			NamedRequirements = { "AlchemyUnlocked" },
			{
				FunctionName = "RequireAffordableGhostAdminItems",
				FunctionArgs =
				{
					CategoryIndex = 1,
					HasNone = { "WorldUpgradeTimeStop" },
				},
			},
		},
		"WorldUpgradeReviveIcarus",
		"WorldUpgradeAmbrosia",
		"WorldUpgradeNectar",
		"WorldUpgradeFamiliarPoints",
		"WorldUpgradeCardUpgradePoints2",
		"WorldUpgradeMixerShadow",
	},
}
